version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: restaurant_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: restaurant_db
      POSTGRES_USER: restaurant_user
      POSTGRES_PASSWORD: restaurant_pass
      TZ: UTC
    command: ["postgres", "-c", "timezone=UTC"]
    ports:
      - "5432:5432"
    volumes:
      - restaurant_postgres_data:/var/lib/postgresql/data

volumes:
  restaurant_postgres_data:
