// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Restaurant.Api.Infrastructure.Persistence;

#nullable disable

namespace Restaurant.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20260503034431_AddPrintJobs")]
    partial class AddPrintJobs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.HasIndex("TenantId", "Action")
                        .HasDatabaseName("ix_audit_logs_tenant_id_action");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_audit_logs_tenant_id_created_at");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bill_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTimeOffset>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<Guid>("PaidByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("paid_by_user_id");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("VoidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voided_at");

                    b.Property<Guid?>("VoidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("voided_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_bills");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_bills_order_id");

                    b.HasIndex("PaidByUserId")
                        .HasDatabaseName("ix_bills_paid_by_user_id");

                    b.HasIndex("VoidedByUserId")
                        .HasDatabaseName("ix_bills_voided_by_user_id");

                    b.HasIndex("TenantId", "BillNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_bills_tenant_id_bill_number");

                    b.HasIndex("TenantId", "OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_bills_tenant_id_order_id");

                    b.HasIndex("TenantId", "PaidAt")
                        .HasDatabaseName("ix_bills_tenant_id_paid_at");

                    b.HasIndex("TenantId", "PaymentType")
                        .HasDatabaseName("ix_bills_tenant_id_payment_type");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_bills_tenant_id_status");

                    b.ToTable("bills", (string)null);
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.BillItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid")
                        .HasColumnName("bill_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ItemNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("item_name_snapshot");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("line_total");

                    b.Property<Guid?>("OrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("UnitPriceSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price_snapshot");

                    b.HasKey("Id")
                        .HasName("pk_bill_items");

                    b.HasIndex("BillId")
                        .HasDatabaseName("ix_bill_items_bill_id");

                    b.HasIndex("OrderItemId")
                        .HasDatabaseName("ix_bill_items_order_item_id");

                    b.HasIndex("TenantId", "BillId")
                        .HasDatabaseName("ix_bill_items_tenant_id_bill_id");

                    b.ToTable("bill_items", (string)null);
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.BillNumberSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("LastSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("last_sequence");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_bill_number_sequences");

                    b.HasIndex("TenantId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_bill_number_sequences_tenant_id_date");

                    b.ToTable("bill_number_sequences", (string)null);
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("ix_categories_tenant_id_is_active");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_tenant_id_name");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ImageObjectKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_object_key");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_available");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_menu_items");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_menu_items_category_id");

                    b.HasIndex("TenantId", "CategoryId")
                        .HasDatabaseName("ix_menu_items_tenant_id_category_id");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("ix_menu_items_tenant_id_is_active");

                    b.HasIndex("TenantId", "IsAvailable")
                        .HasDatabaseName("ix_menu_items_tenant_id_is_available");

                    b.ToTable("menu_items", (string)null);
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<DateTimeOffset?>("SentToKitchenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_to_kitchen_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TableId")
                        .HasColumnType("uuid")
                        .HasColumnName("table_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_orders_created_by_user_id");

                    b.HasIndex("TableId")
                        .HasDatabaseName("ix_orders_table_id");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_orders_tenant_id_created_at");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_orders_tenant_id_status");

                    b.HasIndex("TenantId", "TableId", "Status")
                        .HasDatabaseName("ix_orders_tenant_id_table_id_status");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ItemNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("item_name_snapshot");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("menu_item_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset?>("SentToKitchenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_to_kitchen_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("CancelledByUserId")
                        .HasDatabaseName("ix_order_items_cancelled_by_user_id");

                    b.HasIndex("MenuItemId")
                        .HasDatabaseName("ix_order_items_menu_item_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_order_items_tenant_id_created_at");

                    b.HasIndex("TenantId", "OrderId")
                        .HasDatabaseName("ix_order_items_tenant_id_order_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_order_items_tenant_id_status");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.PrintJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("PrintKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("print_key");

                    b.Property<DateTimeOffset?>("PrintedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("printed_at");

                    b.Property<string>("PrinterType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("printer_type");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_print_jobs");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_print_jobs_tenant_id_created_at");

                    b.HasIndex("TenantId", "PrintKey")
                        .IsUnique()
                        .HasDatabaseName("ix_print_jobs_tenant_id_print_key");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_print_jobs_tenant_id_status");

                    b.HasIndex("TenantId", "PrinterType", "Status")
                        .HasDatabaseName("ix_print_jobs_tenant_id_printer_type_status");

                    b.ToTable("print_jobs", (string)null);
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_expires_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.HasIndex("TenantId", "UserId")
                        .HasDatabaseName("ix_refresh_tokens_tenant_id_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.RestaurantTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_restaurant_tables");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_restaurant_tables_tenant_id_name");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_restaurant_tables_tenant_id_status");

                    b.ToTable("restaurant_tables", (string)null);
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_tenants_status");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_users_tenant_id");

                    b.HasIndex("TenantId", "Role")
                        .HasDatabaseName("ix_users_tenant_id_role");

                    b.HasIndex("TenantId", "Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenant_id_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.VoidLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid")
                        .HasColumnName("bill_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_void_logs");

                    b.HasIndex("BillId")
                        .HasDatabaseName("ix_void_logs_bill_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_void_logs_user_id");

                    b.HasIndex("TenantId", "BillId")
                        .HasDatabaseName("ix_void_logs_tenant_id_bill_id");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_void_logs_tenant_id_created_at");

                    b.HasIndex("TenantId", "UserId")
                        .HasDatabaseName("ix_void_logs_tenant_id_user_id");

                    b.ToTable("void_logs", (string)null);
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Restaurant.Api.Domain.Entities.Tenant", "Tenant")
                        .WithMany("AuditLogs")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_logs_tenants_tenant_id");

                    b.HasOne("Restaurant.Api.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_logs_users_user_id");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.Bill", b =>
                {
                    b.HasOne("Restaurant.Api.Domain.Entities.Order", "Order")
                        .WithOne("Bill")
                        .HasForeignKey("Restaurant.Api.Domain.Entities.Bill", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bills_orders_order_id");

                    b.HasOne("Restaurant.Api.Domain.Entities.User", "PaidByUser")
                        .WithMany("PaidBills")
                        .HasForeignKey("PaidByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bills_users_paid_by_user_id");

                    b.HasOne("Restaurant.Api.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Bills")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bills_tenants_tenant_id");

                    b.HasOne("Restaurant.Api.Domain.Entities.User", "VoidedByUser")
                        .WithMany("VoidedBills")
                        .HasForeignKey("VoidedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_bills_users_voided_by_user_id");

                    b.Navigation("Order");

                    b.Navigation("PaidByUser");

                    b.Navigation("Tenant");

                    b.Navigation("VoidedByUser");
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.BillItem", b =>
                {
                    b.HasOne("Restaurant.Api.Domain.Entities.Bill", "Bill")
                        .WithMany("Items")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bill_items_bills_bill_id");

                    b.HasOne("Restaurant.Api.Domain.Entities.OrderItem", "OrderItem")
                        .WithMany("BillItems")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_bill_items_order_items_order_item_id");

                    b.HasOne("Restaurant.Api.Domain.Entities.Tenant", "Tenant")
                        .WithMany("BillItems")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bill_items_tenants_tenant_id");

                    b.Navigation("Bill");

                    b.Navigation("OrderItem");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.BillNumberSequence", b =>
                {
                    b.HasOne("Restaurant.Api.Domain.Entities.Tenant", "Tenant")
                        .WithMany("BillNumberSequences")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bill_number_sequences_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.Category", b =>
                {
                    b.HasOne("Restaurant.Api.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Categories")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_categories_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.MenuItem", b =>
                {
                    b.HasOne("Restaurant.Api.Domain.Entities.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_menu_items_categories_category_id");

                    b.HasOne("Restaurant.Api.Domain.Entities.Tenant", "Tenant")
                        .WithMany("MenuItems")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_menu_items_tenants_tenant_id");

                    b.Navigation("Category");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.Order", b =>
                {
                    b.HasOne("Restaurant.Api.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedOrders")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_users_created_by_user_id");

                    b.HasOne("Restaurant.Api.Domain.Entities.RestaurantTable", "Table")
                        .WithMany("Orders")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_restaurant_tables_table_id");

                    b.HasOne("Restaurant.Api.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Orders")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_tenants_tenant_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Table");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Restaurant.Api.Domain.Entities.User", "CancelledByUser")
                        .WithMany("CancelledOrderItems")
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_order_items_users_cancelled_by_user_id");

                    b.HasOne("Restaurant.Api.Domain.Entities.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_menu_items_menu_item_id");

                    b.HasOne("Restaurant.Api.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_orders_order_id");

                    b.HasOne("Restaurant.Api.Domain.Entities.Tenant", "Tenant")
                        .WithMany("OrderItems")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_tenants_tenant_id");

                    b.Navigation("CancelledByUser");

                    b.Navigation("MenuItem");

                    b.Navigation("Order");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.PrintJob", b =>
                {
                    b.HasOne("Restaurant.Api.Domain.Entities.Tenant", "Tenant")
                        .WithMany("PrintJobs")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_print_jobs_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Restaurant.Api.Domain.Entities.Tenant", "Tenant")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_tenants_tenant_id");

                    b.HasOne("Restaurant.Api.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.RestaurantTable", b =>
                {
                    b.HasOne("Restaurant.Api.Domain.Entities.Tenant", "Tenant")
                        .WithMany("RestaurantTables")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_restaurant_tables_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.User", b =>
                {
                    b.HasOne("Restaurant.Api.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.VoidLog", b =>
                {
                    b.HasOne("Restaurant.Api.Domain.Entities.Bill", "Bill")
                        .WithMany("VoidLogs")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_void_logs_bills_bill_id");

                    b.HasOne("Restaurant.Api.Domain.Entities.Tenant", "Tenant")
                        .WithMany("VoidLogs")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_void_logs_tenants_tenant_id");

                    b.HasOne("Restaurant.Api.Domain.Entities.User", "User")
                        .WithMany("VoidLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_void_logs_users_user_id");

                    b.Navigation("Bill");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.Bill", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("VoidLogs");
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.MenuItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.Order", b =>
                {
                    b.Navigation("Bill");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.OrderItem", b =>
                {
                    b.Navigation("BillItems");
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.RestaurantTable", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("BillItems");

                    b.Navigation("BillNumberSequences");

                    b.Navigation("Bills");

                    b.Navigation("Categories");

                    b.Navigation("MenuItems");

                    b.Navigation("OrderItems");

                    b.Navigation("Orders");

                    b.Navigation("PrintJobs");

                    b.Navigation("RefreshTokens");

                    b.Navigation("RestaurantTables");

                    b.Navigation("Users");

                    b.Navigation("VoidLogs");
                });

            modelBuilder.Entity("Restaurant.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CancelledOrderItems");

                    b.Navigation("CreatedOrders");

                    b.Navigation("PaidBills");

                    b.Navigation("RefreshTokens");

                    b.Navigation("VoidLogs");

                    b.Navigation("VoidedBills");
                });
#pragma warning restore 612, 618
        }
    }
}
